#!/bin/bash

# change DOCKER_ID to your value
DOCKER_ID=stepkun

# set wanted distro
DISTRO=humble
UBUNTU=22.04

# usable parameters:
LANGUAGE=de_DE.UTF-8
TIMEZONE="Europe/Berlin"
USERNAME=ros
USER_UID=1000
USER_GID=$USER_UID

# create param string from wanted values
PARAMS="--build-arg ROS_DISTRO=$DISTRO \
        --build-arg UBUNTU_VERSION=$UBUNTU \
        --build-arg LANGUAGE=$LANGUAGE \
        --build-arg TIMEZONE=$TIMEZONE \
        --build-arg USERNAME=$USERNAME \
        --build-arg USER_UID=$USER_UID \
        --build-arg USER_GID=$USER_GID"

# creation in layer order bottom up
# possible additional arguments: --no-cache
DOCKER_BUILDKIT=1 docker build --target run  $1 $2 $PARAMS -t $DOCKER_ID/vulcanexus:$DISTRO-run .
DOCKER_BUILDKIT=1 docker build --target dev  $1 $2 $PARAMS -t $DOCKER_ID/vulcanexus:$DISTRO-dev .
DOCKER_BUILDKIT=1 docker build --target full $1 $2 $PARAMS -t $DOCKER_ID/vulcanexus:$DISTRO-full .
DOCKER_BUILDKIT=1 docker build --target sim  $1 $2 $PARAMS -t $DOCKER_ID/vulcanexus:$DISTRO-sim .
