#!/bin/bash
# Copyright (c) 2022-2023 Stephan Kunz
set -e

# change DOCKER_ID to your value
DOCKER_ID=stepkun
DOCKER_PATH=$DOCKER_ID/vulcanexus
# usable parameters:
LANGUAGE=de_DE.UTF-8
TIMEZONE="Europe/Berlin"
USERNAME=ros
USER_UID=1000
USER_GID=$USER_UID

# before running this script you should have installed docker multiplattform support
# on amd64 this can be done with the following two commands:
# sudo docker run --privileged --rm tonistiigi/binfmt --install arm64 amd64
# docker buildx create --use

# currently locally only one platform at a time supported
PLATFORMS="linux/amd64"

# ubuntu version
UBUNTU=22.04
# related distros to that ubuntu version
DISTROS='humble iron'
TARGETS='run dev sim full' # run dev sim full'

# ask for clearance of cache
docker buildx prune
for DISTRO in $DISTROS
do
        # create param string from wanted values
        PARAMS="--build-arg ROS_DISTRO=$DISTRO \
                --build-arg UBUNTU_VERSION=$UBUNTU \
                --build-arg LANGUAGE=$LANGUAGE \
                --build-arg TIMEZONE=$TIMEZONE \
                --build-arg USERNAME=$USERNAME \
                --build-arg USER_UID=$USER_UID \
                --build-arg USER_GID=$USER_GID"
        
        # creation of all layers bottom up and direct push
        for TARGET in $TARGETS
        do
                docker buildx build --load --platform=$PLATFORMS --target=$TARGET $PARAMS --tag=$DOCKER_PATH:$DISTRO-$TARGET .
        done
done
