#!/bin/bash
# change DOCKER_ID to your value
DOCKER_ID=stepkun

docker login
docker push $DOCKER_ID/vulcanexus:humble-run
docker push $DOCKER_ID/vulcanexus:humble-dev
docker push $DOCKER_ID/vulcanexus:humble-full
