#!/bin/bash

# change DOCKER_ID to your value
DOCKER_ID=stepkun

# set wanted distro
DISTRO=humble
UBUNTU=22.04

# usable parameters:
LANGUAGE=de_DE.UTF-8
TIMEZONE="Europe/Berlin"

# create param string from wanted values
PARAMS="--build-arg ROS_DISTRO=$DISTRO \
        --build-arg UBUNTU_VERSION=$UBUNTU \
        --build-arg LANGUAGE=$LANGUAGE \
        --build-arg TIMEZONE=$TIMEZONE"

# creation of all layers for top package "rmf-demos" with --no-cache, than build packages below that
DOCKER_BUILDKIT=1 docker build --no-cache --target demos $PARAMS -t $DOCKER_ID/rmf:$DISTRO-demos .
